services:

  # Primary Containers
  nginx:
    build:
      context: .
      dockerfile: docker/nginx.dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./laravel:/var/www/html
      - ./docker/conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - mysql
      - php

  php:
    build:
      context: .
      dockerfile: docker/php.dockerfile
    volumes:
      - ./laravel:/var/www/html:delegated

  mysql:
    image: mysql:5.7
    env_file:
      - ./docker/env/mysql.env
    volumes:
      - db_data:/var/lib/mysql

  # Utility Containers
  composer:
    build:
      context: ./docker
      dockerfile: composer.dockerfile
    volumes:
      - ./laravel:/var/www/html

  artisan:
    build:
      context: .
      dockerfile: docker/php.dockerfile
    volumes:
      - ./laravel:/var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]

  npm:
    build:
      context: ./docker
      dockerfile: npm.dockerfile
    volumes:
      - ./laravel:/var/www/html

volumes:
  db_data: {}