version: "3.9"

services:
  nginx:
    #image: "nginx:stable-alpine"
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - mysql
      - php
  php:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
  mysql:
    image: "mysql:5.7"
    platform: "linux/x86_64"
    env_file:
      - ./env/mysql.env
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
  artisan:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]
  npm:
    build:
      context: ./dockerfiles
      dockerfile: npm.dockerfile
    volumes:
      - ./src:/var/www/html