services:

  # Primary Containers
  nginx:
    build:
      context: .
      dockerfile: docker/nginx.dockerfile
    ports:
      - "8603:80"
    volumes:
      - ./wordpress:/var/www/html
      - ./docker/conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - mysql
      - php

  php:
    build:
      context: .
      dockerfile: docker/php.dockerfile
    volumes:
      - ./wordpress:/var/www/html:delegated

  mysql:
    image: mysql:8
    # Optional: Force platform if using MacBook with A1 chip (linux/arm64/v8)
    platform: linux/x86_64
    env_file:
      - ./docker/env/mysql.env
    # Optional: Expose port to connect to database locally
    ports:
      - "8604:3306"
    volumes:
      - db_data:/var/lib/mysql

  # Utility Containers
  wp:
    build:
      context: ./docker
      dockerfile: wp.dockerfile
    volumes:
      - ./wordpress:/var/www/html

volumes:
  db_data: {}
