services:

  # Primary Containers
  node:
    build:
      context: .
      dockerfile: docker/node.dockerfile
    ports:
      - "8602:3000"
    volumes:
      - ./vue:/app

  # Utility Containers
  npm:
    build:
      context: .
      dockerfile: docker/npm.dockerfile
    volumes:
      - ./vue:/app